name: Android Debug APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install JS deps
        run: npm ci

      # add android platform only if it's missing
      - name: Ensure Android platform
        run: |
          if [ ! -d android/app ]; then
            npx cap add android --force
          fi

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoonTide-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
