name: Android Debug APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # 1) Check out source
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Toolchains
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3) Install JS / Capacitor dependencies
      - name: Install JS deps
        run: npm ci

      # 4) Ensure the android/ platform exists (no flags, safe if it already exists)
      - name: Ensure Android platform
        run: |
          if [ ! -d android/app ]; then
            npx cap add android
          fi

      # 5) Build the web assets used by Capacitor
      - name: Build web assets
        run: npm run build

      # 6) Copy web assets & plugins into android/
      - name: Sync Capacitor
        run: npx cap sync android

      # 7) Build the debug APK
      - name: Build debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      # 8) Upload the APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoonTide-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
