name: Android Debug APK

on:
  workflow_dispatch:       # run manually
  push:
    branches: [ main ]     # or whenever you push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install JS deps
        run: npm ci

      - name: Cache Gradle
        uses: gradle/gradle-build-action@v2

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoonTide-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk