name: Build Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Web App
    runs-on: ubuntu-latest

    steps:
      # 1) Check out source
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Set up Node 20
      - name: Set up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3) Install dependencies
      - name: Install deps
        run: npm ci

      # 4) Build production
      - name: Build production
        run: npm run build

      # 5) Set up JDK for Android build
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 6) Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # 7) Build Android debug APK
      - name: Build Android APK
        run: npm run android:debug

      # 8) Upload debug APK artifact
      - name: Upload app-debug.apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
